# Generated by Django 5.2.17 on 2026-08-21 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('calculation', 'Calculation issue'), ('usability', 'Something is confusing'), ('missing_feature', 'Missing feature'), ('bug', 'Something is broken'), ('other', 'Other')], max_length=30)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('message', models.TextField(max_length=3000)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='workspaces.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
