# Generated by Django 5.2.17 on 2026-08-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='workspaces.shop')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=120)),
                ('ordered_at', models.DateTimeField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('item_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marketplace_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('profit_status', models.CharField(choices=[('profitable', 'Profitable'), ('low_margin', 'Low margin'), ('loss', 'Loss'), ('incomplete', 'Cost incomplete')], default='incomplete', max_length=20)),
                ('calculation_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.importbatch')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workspaces.shop')),
            ],
            options={
                'ordering': ('-ordered_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FeeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('listing', 'Listing'), ('transaction', 'Transaction'), ('payment', 'Payment processing'), ('etsy_ads', 'Etsy Ads'), ('offsite_ads', 'Offsite Ads'), ('regulatory', 'Regulatory'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_lines', to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('materials', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packaging', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overhead', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_costs', to='workspaces.shop')),
            ],
            options={
                'ordering': ('sku',),
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('shop', 'external_order_id'), name='unique_external_order_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='productcost',
            constraint=models.UniqueConstraint(fields=('shop', 'sku'), name='unique_product_cost_per_shop'),
        ),
    ]
